### ISSUE TITLE
Regenerate Verspaeti Cache on Access

### ISSUE THREAD

**Issue by n0emis** [FahrplanDatenGarten/FahrplanDatenGarten#16]
When the verspaeti-cache is not populated, the website currently shows a messagebox. It would be nice, if this would trigger a celery-job, which regenerates the cache

**Comment by leona-ya** [comment]
I don't think this makes much sense, because the task should be triggered automatically by Celery Beat. If Celery Beat is not running, no journey data is imported, so there is no data to generate statistics for
